checkoutLocation: "."
workspaceLocation: "workspace"

tasks:
  - name: Pull images
    env:
      AIRFLOW_IMAGE_NAME: dmacademy/airflow:2.10.1
    init: |
      docker-compose --file ../docker-compose.yaml pull
      gp sync-done pull

  - name: Boot Airflow
    env:
      AIRFLOW_IMAGE_NAME: dmacademy/airflow:2.10.1
    init: |
      gp sync-await pull
      docker-compose --file ../docker-compose.yaml up airflow-init
    before: |
      mkdir -p ./mount/dags ./mount/logs ./mount/plugins
      echo -e "AIRFLOW_UID=$(id -u)" >> ../.env
    command: |
      docker-compose --file ../docker-compose.yaml up

ports:
  - port: 5555
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
