checkoutLocation: "."
workspaceLocation: "workspace"

tasks:
  - name: Pull images
    init: |
      docker-compose --file ../docker-compose.yml pull
      gp sync-done pull

  - name: Boot Airflow
    init: |
      gp sync-await pull
      docker-compose --file ../docker-compose.yml up airflow-init
    before: |
      mkdir -p ./mount/dags ./mount/logs ./mount/plugins
      echo -e "AIRFLOW_UID=$(id -u)" >> ../.env
      #      docker build . --tag academy-airflow:2.2.3
      #      echo -e "AIRFLOW_IMAGE_NAME=academy-airflow:2.2.3" >> ../.env
      # Make sure to add these to your gitpod variables: https://gitpod.io/variables
      # Their value can be obtained from the "terraform apply" outputs.
      echo -e "AWS_ACCESS_KEY_ID=${AIRFLOW_IAM_ACCESS_KEY}" >> ../.env
      echo -e "AWS_SECRET_ACCESS_KEY=${AIRFLOW_IAM_SECRET_ACCESS_KEY}" >> ../.env
    command: |
      docker-compose --file ../docker-compose.yml up

ports:
  - port: 5555
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-python.python
